# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-test:

    runs-on: self-hosted

    steps:
    - name: 'Run actions'
      uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: 'Install Dependencies'
      run: npm install
    - name: 'Run tests'
      run: npm test

  secret-test:
    needs: unit_tests
    runs-on: self-hosted

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20
    - name: Install dependencies
      run: npm install
    - name: Run security tests
      run: npm audit

  deploy:
      runs-on: self-hosted
      needs: secret-test
      steps:
        - name: Deploy to production
          uses: johnbeynon/render-deploy-action@v0.0.8
          with:
            service-id: ${{ secrets.RENDER_TOKEN }}
            api-key: ${{ secrets.SERVICE_ID }}
            wait-for-success: true    
